version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
