version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: fenced
    main: ./main.go
    binary: fenced
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/unstoppablemango/fenced/cmd.Version={{.Version}}

archives:
  - id: fenced
    formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: UnstoppableMango
    name: fenced
  draft: false
  prerelease: auto
